### ISSUE TITLE
Cowin api permission 

### ISSUE THREAD

**Issue by Tnu02** [SRvSaha/srvsaha#1] opened 2021-06-13 07:45 UTC
https://github.com/yashwanthm/cowin-vaccine-booking/issues/95

Hey @SRvSaha , have a look into this.. is it possible for us as well to take permission !!

**Comment by SRvSaha** [comment] 2021-06-13 08:33
@Tnu02 No, it is not since that needs submission of some Personal Documents at first place. Secondly, the issue is that the whole App needs to be redesigned to have a server in the Middle which would instead call COWIN APIs, that's too much of work and lots of new dependencies on Server Costs and Security of Key. 
I think the Repo you mentioned have not considered the above and hence, even after getting the key, if the architecture is not changed, anyone can get the key used by that repo and then misuse it (as in, let's say some user may get that key and then use it for all requests. As per COWIN requests are coming from the App of the mentioned repo, but instead may be coming from lots of different places).

Closing the Issue as there is no viable solution till now. That being said I have observed that bookings are still going on smooth, so unless you are using the App for 3-4 hours continuously for getting slots booked, you'll be fine.

**Closed by SRvSaha** 2021-06-13 08:33 UTC

**Comment by Tnu02** [comment] 2021-06-13 09:22
I have stopped using it due to the new api rules 😅😅

I usually didn't ping the server continuosly previously also.. Used to opened it as soon as I got the notification from bot and all..

Is it a good approach or I should completely stop using it..!!

**Comment by SRvSaha** [comment] 2021-06-13 09:54
U can use it in that way! No issues @Tnu02

**Comment by Tnu02** [comment] 2021-06-13 10:20
> U can use it in that way! No issues @Tnu02 

Thank you so much @SRvSaha

**Comment by SRvSaha** [comment] 2021-06-13 10:22
Deleting the issue since it's unrelated, @Tnu02
